name: Set up python 3.11 & 3.12, as well as hatch

on:
  workflow_call:

jobs:
  setup:
    name: Configure environment
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11", "3.12"  ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Installing Hatch
        run: pip install --upgrade hatch